#!/bin/bash
# Variables for hlwm
#Terminal emulator to use
TERM=xterm
#Panel script location
PANEL=~/.config/herbstluftwm/scripts/panel/panel.sh
#Startup script
STARTUP=~/.config/herbstluftwm/scripts/misc/startup.sh

#Mod/Super keys
Mod=Mod1
Super=Mod4
echo $TERM
hc() {
    herbstclient "$@"
}
hc emit_hook reload
# Set default wallpaper to glorious arch.png
feh --bg-scale ~/.config/herbstluftwm/arch.png
hc keyunbind --all
hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c quit
hc keybind $Mod-Return spawn $TERM -fg white -bg black -vb -bc +si
# rofi application launcher
hc keybind $Mod-d spawn rofi -show run -fg "#ff0000" -bg "#000000"
hc keybind $Mod-Shift-e spawn ~/.config/herbstluftwm/scripts/layout/restore.sh
hc keybind $Mod-Shift-b spawn ~/.config/herbstluftwm/scripts/layout/backup.sh
hc keybind $Mod-Shift-f spawn ~/.config/herbstluftwm/scripts/layout/delete.sh
hc keybind $Mod-Shift-period spawn ~/.config/herbstluftwm/scripts/tags/new.sh
# Disable/Enable the touchpad
hc keybind $Mod-Shift-i spawn synclient Touchpadoff=0
hc keybind $Mod-Shift-o spawn synclient Touchpadoff=1
# Cycle wallpapers (thanks austen)
hc keybind $Mod-Shift-n spawn ~/.config/herbstluftwm/scripts/misc/shuffle.sh
# Reset to the original boot one
hc keybind $Mod-Shift-m spawn feh --bg-scale ~/.config/herbstluftwm/arch.png
# Lock screen using slimlock
hc keybind $Mod-0 spawn slimlock
# Hide/show the system tray (trayer)
hc keybind $Mod-Shift-s spawn trayer --edge bottom --align right --widthtype request --heighttype pixel --height 14 --expand true --tint 0x222222 --transparent true
hc keybind $Mod-Shift-d spawn killall trayer
# basic movement
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right
# create an empty frame at the specified direction via the split script
hc keybind $Mod-u spawn ~/.config/herbstluftwm/scripts/layout/split bottom .5
hc keybind $Mod-o spawn ~/.config/herbstluftwm/scripts/layout/split right .5
# resizing frames
resizestep=0.05
hc keybind $Mod-$Super-h       resize left +$resizestep
hc keybind $Mod-$Super-j       resize down +$resizestep
hc keybind $Mod-$Super-k       resize up +$resizestep
hc keybind $Mod-$Super-l       resize right +$resizestep
# Create the tags
hc rename default term
hc add web
hc add media
hc add dev
hc add 5
hc add 6
hc add 7
hc add 8
hc keybind $Mod-1 use term
hc keybind $Mod-2 use web
hc keybind $Mod-3 use media
hc keybind $Mod-4 use dev
hc keybind $Mod-5 use 5
hc keybind $Mod-6 use 6
hc keybind $Mod-7 use 7
hc keybind $Mod-8 use 8
hc keybind $Mod-Shift-1 move term
hc keybind $Mod-Shift-2 move web
hc keybind $Mod-Shift-3 move media
hc keybind $Mod-Shift-4 move dev
hc keybind $Mod-Shift-5 move 5
hc keybind $Mod-Shift-6 move 6
hc keybind $Mod-Shift-7 move 7
hc keybind $Mod-Shift-8 move 8
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible 
# layouting
hc keybind $Mod-x remove
hc keybind $Mod-f fullscreen toggle
# focus
# Sloppy focusing
hc set focus_follows_mouse 1
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set frame_border_active_color '#000000'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#CCCCCC'
hc set frame_bg_active_color '#666666' 
hc set frame_border_width 1
hc set window_border_width 1
hc set window_border_normal_color '#000000'
hc set window_border_active_color '#cc0000'
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
# rules
hc unrule -F
hc rule class=Firefox tag=web
hc rule class=Nm-connection-editor fullscreen=on
hc rule class=jetbrains-studio tag=dev
hc rule class=VirtualBox fullscreen=on
hc rule focus=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc load term '(split horizontal:0.500000:0 (split vertical:0.500000:1 (clients vertical:0) (clients grid:0)) (split vertical:0.500000:0 (clients grid:0) (clients grid:0)))'
# unlock, just to be sure
hc unlock
hc set tree_style "X|:#+*-."
~/.config/herbstluftwm/scripts/misc/updatedisplays.sh
#start the panel
#for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
#    "$PANEL" $monitor &
#done
#Run startup script
polybar example
bash $STARTUP &
