#!/bin/bash
hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'
# Set default wallpaper to glorious arch.png
feh --bg-scale ~/.config/herbstluftwm/arch.png

hc keyunbind --all

Mod=Mod1
Super=Mod4

hc keybind $Mod-Shift-q close
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c quit
hc keybind $Mod-Return spawn xterm -fg white -bg black -vb -bc +si
# Dmenu application launcher
hc keybind $Mod-d spawn dmenu_run_hlwm -i
# Quickly edit files on the fly
hc keybind $Mod-s spawn xterm -fg white -bg black -vb -bc +si -e "vim +FZF"
hc keybind $Mod-Shift-e spawn ~/.config/herbstluftwm/restore.sh
hc keybind $Mod-Shift-b spawn ~/.config/herbstluftwm/backup.sh
hc keybind $Mod-Shift-f spawn ~/.config/herbstluftwm/delete.sh
# Disable/Enable the touchpad
hc keybind $Mod-Shift-i spawn synclient Touchpadoff=0
hc keybind $Mod-Shift-o spawn synclient Touchpadoff=1
# Cycle wallpapers (thanks austen)
hc keybind $Mod-Shift-n spawn ~/.config/herbstluftwm/shuffle.sh
# Reset to the original boot one
hc keybind $Mod-Shift-m spawn feh --bg-scale ~/.config/herbstluftwm/arch.png
# Lock screen using slimlock
hc keybind $Mod-0 spawn slimlock
# Hide/show the system tray (trayer)
hc keybind $Mod-Shift-s spawn trayer
hc keybind $Mod-Shift-d spawn killall trayer

# basic movement
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# create an empty frame at the specified direction via the split script
hc keybind $Mod-u spawn ~/.config/herbstluftwm/split bottom .5
hc keybind $Mod-o spawn ~/.config/herbstluftwm/split right .5

# resizing frames
resizestep=0.05
hc keybind $Mod-$Super-h       resize left +$resizestep
hc keybind $Mod-$Super-j       resize down +$resizestep
hc keybind $Mod-$Super-k       resize up +$resizestep
hc keybind $Mod-$Super-l       resize right +$resizestep

# Create the tags
hc rename default term
hc add web
hc add media
hc add 1
hc add 2
hc add 3

hc keybind $Mod-1 use term
hc keybind $Mod-2 use web
hc keybind $Mod-3 use media
hc keybind $Mod-4 use 1
hc keybind $Mod-5 use 2
hc keybind $Mod-6 use 3

hc keybind $Mod-Shift-1 move term
hc keybind $Mod-Shift-2 move web
hc keybind $Mod-Shift-3 move media
hc keybind $Mod-Shift-4 move 1
hc keybind $Mod-Shift-5 move 2
hc keybind $Mod-Shift-6 move 3

# layouting
hc keybind $Mod-x remove
hc keybind $Mod-f fullscreen toggle

# focus

# Sloppy focusing
hc set focus_follows_mouse 1

hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 0
hc set frame_border_active_color '#000000'
hc set frame_border_normal_color '#000000'
hc set frame_bg_normal_color '#CCCCCC'
hc set frame_bg_active_color '#666666' 
hc set frame_border_width 1
hc set window_border_width 1
hc set window_border_normal_color '#000000'
hc set window_border_active_color '#FFFFFF'
hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# rules
hc unrule -F
hc rule class=Firefox tag=web
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

hc set tree_style "X|:#+*-."

/var/scripts/multiMonHerbs.sh

#start the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=~/.config/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    "$panel" $monitor &
done
